<?php

function cipher_menu() {
  $items['encrypt'] = array(
    'title' => 'Encrypt a Message',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cipher_form')
    'access callback' => TRUE,
    'type' => 'MENU_NORMAL_ITEM',
  );
  $items['success'] = array(
    'title' => 'Encrypted Successfully!',
    'page callback' => 'cipher_success',
    'access callback' => TRUE,
    'type' => 'MENU_CALLBACK'
  );

  return $items
}

function cipher_form() {
  $form['shift_value'] = array(
    '#title' => 'Shift Number',
    '#type' => 'textfield',
    '#description' => t('Enter a value to shift your message by'),
    '#element_validate' => array('element_validate_integer_positive'),
    '#required' => TRUE,
  );
  $form['shift_direction'] = array(
    '#title' => 'Shift Direction',
    '#type' => 'textfield',
    '#description' => t('Enter direction to shift (left or right)'),
    '#element_validate' => array('element_validate_direction'),
    '#required' => TRUE,
  );
  $form['shift_phrase'] = array(
    '#title' => 'Message to Encrypt',
    '#type' => 'textfield',
    '#description' => t('What are you trying to hide?'),
    '#element_validate' => '',
    '#required' => TRUE,
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Encrypt Message'
  );
  return $form;
}

function element_validate_direction($element) {
  $direction = $element['$value'];
  $valid_directions = array(
    'left', 'L',
    'right', 'R'
  );

  if (!in_array($direction, $valid_direction)) {
        form_error($element, t('Choose a valid direction to shift.'));
    }
}

function cipher_form_submit($form, &$form_state) {
  $value = $form_state['values']['shift_value'];
  $direction = $form_state['values']['shift_direction'];
  $message = $form_state['values']['shift_phrase'];

}

function cipher_success() {

}
