<?php

function cipher_menu() {
  $items['encrypt'] = array(
    'title' => 'Encrypt a Message',
    'page callback' => 'cipher_encrypt',
    'access callback' => TRUE,
    'type' => 'MENU_NORMAL_ITEM',
  );

  $items['success'] = array(
    'title' => 'Encrypted Successfully!',
    'page callback' => 'cipher_success',
    'access callback' => TRUE,
    'type' => 'MENU_CALLBACK'
  );
}

function cipher_encrypt() {

}

function cipher_success() {

}
